Models/Guestbooks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace final.Models
{
    public class Guestbooks
    {
        [DisplayName("編號：")]
        public int Id { get; set; }
        [DisplayName("名字：")]
        [Required(ErrorMessage = "請輸入名字")]
        [StringLength(20, ErrorMessage = "名字不可超過20 字元")]
        public string Name { get; set; }
        [DisplayName("留言內容：")]
        [Required(ErrorMessage = "請輸入留言內容")]
        [StringLength(100, ErrorMessage = "留言內容不可超過100 字元")]
        public string Content { get; set; }
        [DisplayName("新增時間：")]
        public DateTime CreateTime { get; set; }
        [DisplayName("回覆內容：")]
        [StringLength(100, ErrorMessage = "回覆內容不可超過100 字元")]
        public string Reply { get; set; }
        [DisplayName("回覆時間：")]
        public DateTime? ReplyTime { get; set; }
    }

}

ViewModels/GuestbooksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel;
using final.Models;
using final.Serivces;

namespace final.ViewModels
{
    public class GuestbooksViewModel
    {

        // 搜尋欄位
        [DisplayName(" 搜尋：")]
        public string Search { get; set; }
        //顯示資料陣列
        public List<Guestbooks> DataList { get; set; }
    }
}

Controllers/GuestbooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using final.Models;
using final.Serivces;
using final.ViewModels;
namespace final.Controllers
{
    public class GuestbooksController : Controller
    {
        //宣告Guestbooks資料表的Service物件
        private readonly GuestbooksDBService GuestbookService = new GuestbooksDBService();
        public ActionResult Index(string Search)
        {
            //宣告一個新頁面模型
            GuestbooksViewModel Data = new GuestbooksViewModel();
            //從Service 中取得頁面所需陣列資料
            Data.Search = Search;
            Data.DataList = GuestbookService.GetDataList(Data.Search);
           
            //將頁面資料傳入View 中
            return View(Data);
        }
        #region 新增留言
        // 新增留言一開始載入頁面
        public ActionResult Create()
        {
            return PartialView(); // 因為此頁面用於載入至開始頁面中，故使用部分檢視回傳
        }
        // 新增留言傳入資料時的Action
        [HttpPost] // 設定此Action 只接受頁面POST 資料傳入
                   // 使用Bind 的 Include 來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Create([Bind(Include = "Name, Content")] Guestbooks Data)
        {
            GuestbookService.InsertGuestbooks(Data); // 使用Service 來新增一筆資料
            return RedirectToAction("Index"); // 重新導向頁面至開始頁面
        }
        #endregion

        #region 修改留言
        // 修改留言頁面要根據傳入編號來決定要修改的資料
        public ActionResult Edit(int Id)
        {
            // 取得頁面所需資料，藉由Service 取得
            Guestbooks Data = GuestbookService.GetDataById(Id);
            // 將資料傳入View 中
            return View(Data);
        }

        // 修改留言傳入資料時的Action
        [HttpPost] // 設定此Action 只接受頁面POST 資料傳入

        // 使用Bind 的Inculde 來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Edit(int Id, [Bind(Include = "Name, Content")] Guestbooks UpdateData)
        {
            // 修改資料的是否可修改判斷
            if (GuestbookService.CheckUpdate(Id))
            {
                // 將編號設定至修改資料中
                UpdateData.Id = Id;
                // 使用Service 來修改資料
                GuestbookService.UpdateGuestbooks(UpdateData);

                // 重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
            else
            {
                // 重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
        }
        #endregion


        #region 回覆留言
        // 回覆留言頁面要根據傳入編號來決定要回覆的資料
        public ActionResult Reply(int Id)
        {
            // 取得頁面所需資料，藉由Service 取得
            Guestbooks Data = GuestbookService.GetDataById(Id);
            // 將資料傳入View 中
            return View(Data);
        }
        // 修改留言傳入資料時的Action
        [HttpPost] // 設定此Action 只接受頁面POST 資料傳入

        // 使用Bind 的Inculde 來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Reply(int Id, [Bind(Include = "Reply,ReplyTime")] Guestbooks ReplyData)
        {
            // 修改資料的是否可修改判斷
            if (GuestbookService.CheckUpdate(Id))
            {
                // 將編號設定至回覆留言資料中
                ReplyData.Id = Id;
                // 使用Service 來回覆留言資料
                GuestbookService.ReplyGuestbooks(ReplyData);
                // 重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
            else
            {
                // 重新導向頁面至開始頁面
                return RedirectToAction("Index");
            }
        }
        #endregion


        #region 刪除留言
        // 刪除頁面要根據傳入編號來刪除資料
        public ActionResult Delete(int Id)
        {
            // 使用Service 來刪除資料
            GuestbookService.DeleteGuestbooks(Id);
            // 重新導向頁面至開始頁面
            return RedirectToAction("Index");
        }
        #endregion


       

    }
}

Views/Guestbooks/Create.cshtml
@model final.Models.Guestbooks


@* 建立新增資料所須的表單*@
@using (Html.BeginForm("Create", "Guestbooks"))
{
    <h3> 新增留言</h3>
    <table>
        @* 新增姓名欄位區塊*@
        <tr>
            <td>
                @Html.LabelFor(model => model.Name)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>

        @* 新增內容欄位區塊*@
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
    </table>
    <input type="submit" value=" 新增留言" />
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Guestbooks/Edit.cshtml
@model final.Models.Guestbooks

@{
    ViewBag.Title = "修改留言";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@* 匯入驗證欄位所須的JavaScript*@
@* 匯入驗證欄位所須的JavaScript*@
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval.js")
}

@* 建立修改留言表格*@
<div class="container">
    @using (Html.BeginForm())
    {
        <h3> 修改留言</h3>
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Name)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Content)
                </td>
                <td>
                    @Html.TextBoxFor(model => model.Content)
                    @Html.ValidationMessageFor(model => model.Content)
                </td>
            </tr>
        </table>

        @* 判斷是否有人回覆，如果無人回覆，即可修改，否則不可修改*@

        if (Model.ReplyTime == null)
        {
            <input type="submit" value=" 修改留言" />
        }
        else
        {
            <text> 此留言已回覆無法修改，請</text>
            @Html.ActionLink(" 返回列表", "Index")
        }
    }
</div>

Views/Guestbooks/Reply.cshtml
@model final.Models.Guestbooks

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")

@{
    ViewBag.Title = "回覆留言";
}

@*建立回覆留言所須的表單*@
@using (Html.BeginForm())
{
    <h3> 回覆留言</h3>
    @*建立回覆內容表格 *@

    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Name)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Reply)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Reply)
                @Html.ValidationMessageFor(model => model.Reply)
            </td>
        </tr>
    </table>
    @*一則留言僅可回覆一次，若被回覆，則顯示返回列表連結*@
    if (Model.ReplyTime == null)
    {
        <input type="submit" value=" 回覆留言" />
    }
    else
    {
        <text> 此留言已回覆，請</text>
        @Html.ActionLink(" 返回列表", "Index")
    }
 }

Views/Guestbooks/index.cshtml
@model final.ViewModels.GuestbooksViewModel

@{
    ViewBag.Title = "about";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<title>聯絡我們</title>
<div class="container">
    @* 載入新增留言頁面*@
    <div id="CreateData">
        @Html.Action("Create")
    </div>
    <h2>留言板</h2>
    @* 建立搜尋所須的表單*@
    @using (Html.BeginForm("Index", "Guestbooks", FormMethod.Get))
    {
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Search)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Search)
        </td>
        <td>
            <input type="submit" value=" 搜尋" />
        </td>
    </tr>
</table>
}


    <table>
        @* 如果資料庫中不是零筆記錄，則顯示資料，並列出新增、刪除與修改連結*@
        @if (!Model.DataList.Count.Equals(0))
        {
            foreach (var item in Model.DataList)
            {
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Name)
                    </td>
                    <td>
                        @item.Name
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].CreateTime)
                    </td>
                    <td>
                        @item.CreateTime
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Content)
                    </td>
                    <td colspan="3">
                        @item.Content
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].Reply)
                    </td>
                    <td colspan="3">
                        @item.Reply
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.DataList[0].ReplyTime)
                    </td>
                    <td>
                        @item.ReplyTime
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        @Html.ActionLink(" 修改留言", "Edit", new { Id = item.Id })
                        @Html.ActionLink(" 回覆留言", "Reply", new { Id = item.Id })
                        @Html.ActionLink(" 刪除留言", "Delete", new { Id = item.Id })
                    </td>
                </tr>
            }
        }
        @* 如果資料庫中為零筆記錄，則印出" 資料庫內查無資料"*@
        else
        {
            <tr>
                <td colspan="4">
                    資料庫內查無資料
                </td>
            </tr>
        }
    </table>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@* 匯入驗證欄位所須的JavaScript*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}