ViewModels/DepEmpViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel;
using final.Models;
using final.Services;

namespace final.ViewModels
{
    public class DepEmpViewModel
    {
        public int SrhId { get; set; }
        public string SrhName { get; set; }
        public List<Department> depList { get; set; }
        public List<Employee> empList { get; set; }
    }
}

Controllers/DepEmpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

using final.Models;
using final.Services;
using final.ViewModels;

namespace final.Controllers
{
    public class DepEmpController : Controller
    {
        //宣告Guestbooks資料表的Service物件
        private readonly DepEmpDBService DepEmpService = new DepEmpDBService();
        // GET: DepEmp
        public ActionResult Index(int depid = 1)
        {
            //宣告一個新頁面模型
            DepEmpViewModel Data = new DepEmpViewModel();

            //從Service 中取得分類的資料
            Data.depList = DepEmpService.GetDepList();

            //從Service 中取得分類的商品資料
            Data.empList = DepEmpService.GetEmpList(depid);

            //從Service 中取得分類的名稱
            Data.SrhId = depid;
            Data.SrhName = DepEmpService.GetDepName(depid);

            return View(Data);
        }
        //新增商品
        public ActionResult Create(int dId)
        {
            // 取得頁面所需資料，藉由Service 取得
            List<Department> depList = new List<Department>();
            ViewBag.depList = DepEmpService.GetDepList();
            ViewBag.dId = dId;
            // 將分類資料傳入View 中
            return View();
        }
        // 新增商品傳入資料時的Action
        [HttpPost] // 設定此Action 只接受頁面POST 資料傳入
        // 使用Bind 的 Include 來定義只接受的欄位，用來避免傳入其他不相干的值
        public ActionResult Create([Bind(Include = "EmpId, EmpName, EmpPhone, DepId, upload")] Employee Data)
        {
            if (Data.upload != null)
            {
                string img = Path.Combine(Server.MapPath("~/Images/"), Data.upload.FileName);
                Data.upload.SaveAs(img);
                Data.Img = Data.upload.FileName;
                DepEmpService.InsertEmp(Data);
            }
            else
            {
                ModelState.AddModelError("upload", "upload images");
                ViewBag.depList = DepEmpService.GetDepList();
                return View(Data);
            }
            return RedirectToAction("Index", new { depid = Data.DepId }); // 重新導向頁面至開始頁面
        }

        public ActionResult Edit(string eId)
        {
            // 取得頁面所需資料，藉由Service 取得
            Employee Data = DepEmpService.GetEmpById(eId);
            // 將資料傳入View 中
            if (Data == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(Data);
            }
            // 修改商品資料傳入資料時的Action

        }
        [HttpPost] // 設定此Action 只接受頁面POST 資料傳入

        // 使用Bind 的Inculde 來定義只接受的欄位，用來避免傳入其他不相干值
        public ActionResult Edit(string eId, [Bind(Include = "empId,EmpName,EmpPhone,DepId")] Employee UpdateData)
        {
            // 將編號設定至修改資料中
            UpdateData.EmpId = eId;
            // 使用Service 來修改資料
            DepEmpService.UpdateEmp(UpdateData);

            // 重新導向頁面至開始頁面
            return RedirectToAction("Index", new { depid = UpdateData.DepId });
        }

        // 刪除頁面要根據傳入編號來刪除資料
        public ActionResult Delete(string eId, int dId)
        {
            // 使用Service 來刪除資料
            DepEmpService.DeleteEmp(eId.Trim());
            // 重新導向頁面至開始頁面
            return RedirectToAction("Index", new { depid = dId });
        }
    }
}

Views/DepEmp/Create.cshtml
@model final.Models.Employee
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="container">
    <h2>新增商品</h2>
    @* 建立新增資料所須的表單*@
    @using (Html.BeginForm("Create", "DepEmp", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
<div class="form-horizontal">
    <div class="form-group">
        <label for="DepId" class="control-label col-sm-2"> 分類 </label>
        <div class="col-sm-10">
            <select id="DepId" name="DepId" class="form-control">
                @foreach (var item in ViewBag.depList)
                {
                    if (ViewBag.dId == item.DepId)
                    {
                        <option value="@item.DepId" selected="selected">@item.DepName</option>
                    }
                    else
                    {
                        <option value="@item.DepId">@item.DepName</option>
                    }
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="DepId" class="control-label col-sm-2">商品編號  </label>
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.EmpId)
            @Html.ValidationMessageFor(model => model.EmpId)
        </div>
    </div>
    <div class="form-group">
        <label for="DepId" class="control-label col-sm-2"> 商品名稱 </label>
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.EmpName)
            @Html.ValidationMessageFor(model => model.EmpName)
        </div>
    </div>
    <div class="form-group">
        <label for="DepId" class="control-label col-sm-2">商品簡介</label>
        <div class="col-sm-10">
            @Html.TextBoxFor(model => model.EmpPhone)
            @Html.ValidationMessageFor(model => model.EmpPhone)
        </div>
    </div>
    <div class="form-group">
        <label for="Tid" class="control-label col-sm-2">商品圖片</label>
        <div class="col-sm-10">
            <input type="file" name="upload" id="file" accept="Images/*">
            @Html.ValidationMessageFor(model => model.upload)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" value=" 新增商品" />
        </div>
    </div>
</div>
    }
    <hr />
    <div>
        @Html.ActionLink("回到首頁", "Index", "DepEmp")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/DepEmp/Edit.cshtml
@model final.Models.Employee

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@{
    ViewBag.Title = "Edit";
}
@* 建立修改欄位所須的表單*@


@using (Html.BeginForm())
{
    <h3> 修改商品資料</h3>
    @* 建立修改員工資料表格*@
    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.EmpName)
            </td>
            <td>
                @Html.TextBoxFor(model => model.EmpName)
                @Html.ValidationMessageFor(model => model.EmpName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.EmpPhone)
            </td>
            <td>
                @Html.TextBoxFor(model => model.EmpPhone)
                @Html.ValidationMessageFor(model => model.EmpPhone)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.DepId)
            </td>
            <td>
                @Html.TextBoxFor(model => model.DepId)
                @Html.ValidationMessageFor(model => model.DepId)
            </td>
        </tr>
    </table>
    <input type="submit" value=" 修改" />

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/DepEmp/Index.cshtml
@model final.ViewModels.DepEmpViewModel

@{
    ViewBag.Title = "商店";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="container">
    <h2>低價屋</h2>
    <div class="row">
        <div class="col-md-3">
            <h3>分類</h3><hr />
            @if (!Model.depList.Count.Equals(0))
            {
                foreach (var item in Model.depList)
                {
                    <p>@Html.ActionLink(item.DepName, "Index", new { depid = item.DepId })</p>
                }
            }
            else
            {
                <p>查無資料</p>
            }

        </div>
        <a href="@Url.Action("Create", new {dId=@Model.SrhId })" class="btn btn-info">新增</a>
        <h3>@Model.SrhName</h3>

        @if (!Model.empList.Count.Equals(0))
        {
            foreach (var item in Model.empList)
            {
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img src="@Url.Content("~/Images/"+item.Img)">
                        <div class="caption">
                            <h3>@item.EmpName</h3>
                            <p>@item.EmpPhone</p>
                            <p>
                                @Html.ActionLink(" 修改", "Edit", new { eId = item.EmpId.Trim() })
                                @Html.ActionLink(" 刪除", "Delete", new { eId = item.EmpId.Trim(), dId = item.DepId }, new { onclick = "return confirm('確認刪除');" })
                            </p>
                        </div>
                    </div>
                </div>
            }
        }
        @* 如果資料庫中為零筆記錄，則印出" 資料庫內查無資料"*@
        else
        {
            <p>資料庫內查無資料</p>
        }
    </div>
    </div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}